name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g. 0.3.1)
        required: true
      draft:
        description: Create as draft?
        required: false
        default: "false"
      prerelease:
        description: Mark as prerelease?
        required: false
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BINARY_NAME: zs

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2

      - name: Run Zig tests
        run: zig test src/main.zig

      - name: Build (windows x86_64)
        run: zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseFast --prefix zig-out-windows

      - name: Prepare assets
        run: |
          set -e
          mkdir -p dist
          if [ -f "zig-out-windows/bin/$BINARY_NAME.exe" ]; then
            cp zig-out-windows/bin/$BINARY_NAME.exe dist/${BINARY_NAME}-windows-x86_64.exe
          else
            echo "Binary not found"; exit 1
          fi
          (cd dist && for f in *; do sha256sum "$f" > "$f".sha256; done)
          ls -l dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          body: |
            Manual release for version v${{ inputs.version }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
